<?php
return array (
  'cfg_sitename' => '立刻钱包',
  'cfg_sitetitle' => '立刻钱包',
  'cfg_siteurl' => 'http://wallet.likezhifu.cn',
  'cfg_sitekeywords' => '立刻钱包',
  'cfg_sitedescription' => '立刻钱包',
  'cfg_siteclosed' => '0',
  'cfg_siteclosemsg' => '',
  'cfg_siteicp' => '',
  'cfg_sitecode' => '',
  'cfg_minmoney' => '100',
  'cfg_maxmoney' => '10000',
  'cfg_definamoney' => '100',
  'cfg_dkmonths' => '1,2',
  'cfg_definamonth' => '1',
  'cfg_rixi' => '0.0005',
  'cfg_fuwufei' => '0.001',
  'cfg_shenhefei' => '0.001',
  'cfg_yuqirixi' => '0.01',
  'cfg_yuqifuwufei' => '10',
  'cfg_huankuanri' => '10',
  'cfg_autodisdk' => '1',
  'cfg_autodisdkday' => '1',
  'cfg_disdkdleyday' => '1',
  'cfg_smssid' => 'c99212fb54974384bf52ad6f669311eb',
  'cfg_smstoken' => '7afa4cf44cab450eaa02fe352ee42010',
  'cfg_smsname' => '立刻钱包',
  'cfg_smsmaxcount' => '10',
  'cfg_payuserseller' => '918343',
  'cfg_client_id' => 'k17e559yipd5w7z0kx9gipam',
  'cfg_client_secret' => 'kpbejnrwa0vkbf1hotpu73psil5i9oep',
);